apiVersion: v1
kind: Service
metadata:
  name: {{ with .Values.names.service }}
  {{- . }}
  {{- else }}
  {{- include "mysql.fullname" . }}
  {{- end }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
