# k8s/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: market-analysis-webapp
    type: backend
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2  # 必要に応じてレプリカ数を調整
  selector:
    matchLabels:
      app: market-analysis-webapp
      type: backend
  template:
    metadata:
      labels:
        app: market-analysis-webapp
        type: backend
    spec:
      containers:
      - name: backend-container
        image: ghcr.io/yakibuta888/market_analysis_webapp/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
      imagePullSecrets:
      - name: ghcr-credentials
