# k8s/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: market-analysis-webapp
    type: redis
spec:
  selector:
    app: market-analysis-webapp
    type: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
