apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.names.secret }}
  {{- .Values.names.secret }}
  {{- else }}
  {{- include "backend.fullname" . }}
  {{- end }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: {{ with .Values.secretType | default "Opaque" }}
{{- . | quote }}
{{- end }}
data: {{- with .Values.secretData }}
{{- toYaml . | nindent 2 }}
{{- end }}
