apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-scaling
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-scaling
  template:
    metadata:
      labels:
        service: test-scaling
        app: test-scaling
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "env" # match with node's label
                operator: In
                values:
                - "staging"
              - key: "unmanaged-node" # match with node's label
                operator: In
                values:
                - "true"
      tolerations: # match with node's taint
      - key: "staging-only"
        operator: "Equal"
        value: "true"
        effect: "PreferNoSchedule"
      containers:
      - image: nginx
        name: test-scaling
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi