version: '3.8'

services:
  # frontend:
  #   volumes:
  #     - ./frontend:$WORK_DIR:cached
  #     - vscode-extension-volume:$HOME_DIR/.vscode-server/extensions
  #     - ./.devcontainer/devcontainer-entrypoint.sh:$HOME_DIR/etc/devcontainer-entrypoint.sh
  #   user: $USER_ID:$GROUP_ID
  #   entrypoint:
  #     - bash
  #     - $HOME_DIR/etc/devcontainer-entrypoint.sh
  #   ports:
  #     - $IP:9229:9229
  #   command: npm run dev:debug

  backend:
    build:
      dockerfile: Dockerfile.dev
      shm_size: 1gb
    volumes:
      - ./backend:$WORK_DIR:cached
      - pip-volume:$WORK_DIR/vendor
      - vscode-extension-volume:$HOME_DIR/.vscode-server/extensions
      - ./.devcontainer/devcontainer-entrypoint.sh:$HOME_DIR/etc/devcontainer-entrypoint.sh
    user: $USER_ID:$GROUP_ID
    entrypoint:
      - bash
      - $HOME_DIR/etc/devcontainer-entrypoint.sh
    ports:
      - $IP:6080:80
    command: sleep infinity

volumes:
  pip-volume:
  vscode-extension-volume: {}
