apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: market-analysis-project
  namespace: argocd
spec:
  description: Market Analysis Webapp Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
