apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.names.service }}
  {{- .Values.names.service }}
  {{- else }}
  {{- include "frontend.fullname" . }}
  {{- end }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
