# k8s/redis/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: market-analysis-webapp
    type: redis
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1  # 必要に応じてレプリカ数を調整
  selector:
    matchLabels:
      app: market-analysis-webapp
      type: redis
  template:
    metadata:
      labels:
        app: market-analysis-webapp
        type: redis
    spec:
      containers:
      - name: redis-container
        image: redis:6.2.5
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
