apiVersion: v1
kind: Service
metadata:
  name: {{ with .Values.names.service }}
  {{- . }}
  {{- else }}
  {{- include "redis.fullname" . }}
  {{- end }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
