name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/backend:latest
          ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
        build-args: |
          USERNAME=${{ secrets.USER_NAME }}
          USERID=${{ secrets.USER_ID }}
          GROUPID=${{ secrets.GROUP_ID }}
          HOME_DIR=${{ secrets.HOME_DIR }}
          WORK_DIR=${{ secrets.WORK_DIR }}

    - name: Verify Published Image
      run: |
        docker pull ghcr.io/${{ github.repository }}/backend:latest
        docker image inspect ghcr.io/${{ github.repository }}/backend:latest
        echo "The Docker image has been pushed to GHCR successfully."

    - name: Scan image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}/backend:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true

    - name: Run tests with pytest
      run: |
        pip install -r requirements.txt
        pytest
