name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd frontend
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Run Vitest
      run: |
        cd frontend
        npx vitest --coverage.enabled true

    - name: Upload Coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: frontend/coverage

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/frontend:latest
          ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
        build-args: |
          WORKDIR=${{ secrets.WORK_DIR }}

    - name: Verify Published Image
      run: |
        docker pull ghcr.io/${{ github.repository }}/frontend:latest
        docker image inspect ghcr.io/${{ github.repository }}/frontend:latest
        echo "The Docker image has been pushed to GHCR successfully."

    - name: Scan image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}/frontend:latest'
        format: 'table'
        output: 'trivy-results.table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        cache-dir: '.trivycache'  # キャッシュディレクトリを指定
        github-pat: ${{ secrets.GITHUB_TOKEN }}  # GitHubのPATを使用して認証

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
